// Code generated by github.com/goccy/cgo-math/cmd/cgo-math-bindgen. DO NOT EDIT!
package ccall

import (
	"C"
	_ "unsafe"

	_ "github.com/goccy/cgo-math"
)

//export fabs
//go:linkname fabs github.com/goccy/cgo-math.fabs
func fabs(x C.double) C.double

//export acos
//go:linkname acos github.com/goccy/cgo-math.acos
func acos(x C.double) C.double

//export acosf
//go:linkname acosf github.com/goccy/cgo-math.acosf
func acosf(x C.float) C.float

//export acosh
//go:linkname acosh github.com/goccy/cgo-math.acosh
func acosh(x C.double) C.double

//export asin
//go:linkname asin github.com/goccy/cgo-math.asin
func asin(x C.double) C.double

//export asinh
//go:linkname asinh github.com/goccy/cgo-math.asinh
func asinh(x C.double) C.double

//export atan
//go:linkname atan github.com/goccy/cgo-math.atan
func atan(x C.double) C.double

//export atanh
//go:linkname atanh github.com/goccy/cgo-math.atanh
func atanh(x C.double) C.double

//export atan2
//go:linkname atan2 github.com/goccy/cgo-math.atan2
func atan2(y C.double, x C.double) C.double

//export cbrt
//go:linkname cbrt github.com/goccy/cgo-math.cbrt
func cbrt(x C.double) C.double

//export ceil
//go:linkname ceil github.com/goccy/cgo-math.ceil
func ceil(x C.double) C.double

//export copysign
//go:linkname copysign github.com/goccy/cgo-math.copysign
func copysign(x C.double, y C.double) C.double

//export cos
//go:linkname cos github.com/goccy/cgo-math.cos
func cos(x C.double) C.double

//export cosh
//go:linkname cosh github.com/goccy/cgo-math.cosh
func cosh(x C.double) C.double

//export fdim
//go:linkname fdim github.com/goccy/cgo-math.fdim
func fdim(x C.double, y C.double) C.double

//export erf
//go:linkname erf github.com/goccy/cgo-math.erf
func erf(x C.double) C.double

//export erfc
//go:linkname erfc github.com/goccy/cgo-math.erfc
func erfc(x C.double) C.double

//export exp
//go:linkname exp github.com/goccy/cgo-math.exp
func exp(x C.double) C.double

//export exp2
//go:linkname exp2 github.com/goccy/cgo-math.exp2
func exp2(x C.double) C.double

//export expm1
//go:linkname expm1 github.com/goccy/cgo-math.expm1
func expm1(x C.double) C.double

//export floor
//go:linkname floor github.com/goccy/cgo-math.floor
func floor(x C.double) C.double

//export frexp
//go:linkname frexp github.com/goccy/cgo-math.frexp
func frexp(f C.double, expptr *C.int) C.double

//export log
//go:linkname log github.com/goccy/cgo-math.log
func log(x C.double) C.double

//export log10
//go:linkname log10 github.com/goccy/cgo-math.log10
func log10(x C.double) C.double

//export fmax
//go:linkname fmax github.com/goccy/cgo-math.fmax
func fmax(x C.double, y C.double) C.double

//export fmin
//go:linkname fmin github.com/goccy/cgo-math.fmin
func fmin(x C.double, y C.double) C.double

//export pow
//go:linkname pow github.com/goccy/cgo-math.pow
func pow(x C.double, y C.double) C.double

//export round
//go:linkname round github.com/goccy/cgo-math.round
func round(x C.double) C.double

//export sqrt
//go:linkname sqrt github.com/goccy/cgo-math.sqrt
func sqrt(x C.double) C.double

//export sin
//go:linkname sin github.com/goccy/cgo-math.sin
func sin(x C.double) C.double

//export sinh
//go:linkname sinh github.com/goccy/cgo-math.sinh
func sinh(x C.double) C.double

//export tan
//go:linkname tan github.com/goccy/cgo-math.tan
func tan(x C.double) C.double

//export tanh
//go:linkname tanh github.com/goccy/cgo-math.tanh
func tanh(x C.double) C.double
